title: "GreenDoc Theme"
description: "Documentation for the Open and Sustainable Documentation Theme"
baseurl: "/greendoc_theme" # Adjust if you're hosting on GitHub Pages
url: "https://open-and-sustainable.github.io"
theme: greendoc_theme

remote_theme: Open-and-Sustainable/greendoc_theme