title: "GreenDoc Theme"
description: "Documentation for the Open and Sustainable Documentation Theme"
baseurl: "/greendoc_theme" # Adjust if you're hosting on GitHub Pages
logo: "{{ '/assets/images/logo.png' | relative_url }}"
favicon: "{{ '/assets/images/favicon.ico' | relative_url }}"
url: "https://open-and-sustainable.github.io"
#theme: greendoc_theme
remote_theme: Open-and-Sustainable/greendoc_theme
nav_links:
  - name: "Usage"
    url: "/usage.html"
  - name: "Customization"
    url: "/customization.html"

plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 3
  no_toc_section_class: 'no_toc'
  list_type: 'ul'

#logo: "/assets/images/custom-logo.png"
#favicon: "/assets/images/custom-favicon.ico"
# Customizable Nav Bar Colors
#nav_background_color: "#007BFF" # Override nav bar color (blue)
#nav_hover_color: "#0056b3"      # Override hover color (darker blue)
#nav_link_color: "#ffffff"       # Override link text color (white)

